services:
- type: web
  name: bernhard.xapi
  runtime: static
  repo: https://github.com/bernhard-xapi/xapi
  branch: docs
  buildCommand: |
    HUGO_VERSION=0.143.1; T="hugo_${HUGO_VERSION}_Linux-64bit.tar.gz";
    if [ ! -x $XDG_CACHE_HOME/hugo ]; then mkdir -p ~/tmp;
      wget -P ~/tmp https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/${T};
      cd ~/tmp; tar -xzvf ${T}; mv hugo $XDG_CACHE_HOME/hugo; cd $HOME/project/src/doc;
    fi;$XDG_CACHE_HOME/hugo --gc --minify -b https://bernhard.xapi.onrender.com
  staticPublishPath: public
  buildFilter:
    paths:
    - doc
  rootDir: doc
  previews:
    generation: automatic
version: "1"
